language: go
go:
    - 1.6
    - 1.7
    - tip
install:
    - go get github.com/Masterminds/glide
    - go get github.com/mattn/goveralls
    - glide install
script:
    - goveralls -service=travis-ci
matrix:
  allow_failures:
    - go: tip
